[tool.poetry]
name = "tron"
version = "0.1.0"
description = ""
authors = ["Jag_k <jag.konon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.1.0"
Pillow = "^8.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
